### ISSUE TITLE
[e2e] Testcafe is failing

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#750]
after upgrading dependencies in #745

```
$ cross-env NODE_ENV=production testcafe electron:./ ./e2e/**/*.e2e.ts
ERROR Was unable to open the browser "electron:./" due to error.

Error: Unable to connect
    at NodeDebug._callee2$ (asgardex-electron/node_modules/testcafe-browser-provider-electron/lib/node-debug.js:158:39)
    at tryCatch (asgardex-electron/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (asgardex-electron/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (asgardex-electron/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (asgardex-electron/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at asgardex-electron/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

Type "testcafe -h" for help.
```

At a first view It looks similar to https://github.com/DevExpress/testcafe-browser-provider-electron/issues/59

**Comment by veado** [comment]
Fixed by #2229
